### ISSUE TITLE
command not found: compdef

### ISSUE THREAD

**Issue by jtr860830** [skywind3000/z.lua#94]
When my zsh start and init z.lua always output `(eval):71: command not found: compdef` . Maybe someone can tell me how to fix this. Thx.

- OS: Arch Linux
- zsh version: 5.8
- init script: `eval "$(lua Z.LUA_REPO/z.lua --init zsh enhanced)"`

**Comment by skywind3000** [comment]
Try deleting your .zcompdump files:
rm ~/.zcompdump*

**Comment by skywind3000** [comment]
and try previous version please:

[z.zip](https://github.com/skywind3000/z.lua/files/4291791/z.zip)

**Comment by jtr860830** [comment]
Thanks for replying! Previous version works well. This situation start to occur after I update z.lua. Is the best solution for now is rollback to previous version?

**Comment by skywind3000** [comment]
We can't just simply revert this change, the previous `compctl` is deprecated and may not work any more in the future, while the new `compdef` is recommended since zsh 3.1.6.

see:
https://github.com/skywind3000/z.lua/pull/93

and some incorrect zsh configuration may cause problem, see here:

https://github.com/ohmyzsh/ohmyzsh/issues/7171#issuecomment-428310627

We would ask @Aloxaf for a proper solution.

**Comment by jtr860830** [comment]
I get it. Thx!

**Comment by skywind3000** [comment]
@Aloxaf the new `compdef` may be unavailable without:

```zsh
autoload -Uz compinit
compinit
```

I can reproduce this issue by deleting my `~/.zshrc` and `~/.zshrc.zwc`, can we detect `compinit` ? if zsh completion system hasn't been initialized, just skip the `compdef` command ? 

If not, append a ` 2> /dev/null` after `compdef` ??

**Comment by jtr860830** [comment]
@skywind3000 I put init script after `compinit`. It works well now.

**Comment by skywind3000** [comment]
Ok, I redirect this error message to `/dev/null` in the latest version.
